### ISSUE TITLE
sd_ekho崩溃

### ISSUE THREAD

**Issue by hgneng** [hgneng/ekho#33]
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/speech-dispatcher-modules/sd_ekho /home/hgneng/.config/speech-dispatch'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f1b2aa31a1 in sonicReadShortFromStream (stream=0x0, samples=0x7ff240932d20, maxSamples=8192) at sonic/sonic.c:460
460	sonic/sonic.c: 没有那个文件或目录.
[Current thread is 1 (Thread 0x7ff259c9e700 (LWP 1581))]
(gdb) bt
#0  0x000055f1b2aa31a1 in sonicReadShortFromStream (stream=0x0, samples=0x7ff240932d20, maxSamples=8192) at sonic/sonic.c:460
#1  0x000055f1b2a4e7bc in ekho::EkhoImpl::writePcm (pcm=0x7ff24005d120, frames=10944, arg=0x7ff25f4a2010, 
    type=ekho::OVERLAP_QUIET_PART, tofile=false) at src/libekho_impl.cpp:594
#2  0x000055f1b2a4d43b in ekho::EkhoImpl::speakPcm (pcm=0x7ff24005d120, frames=10944, arg=0x7ff25f4a2010, 
    type=ekho::OVERLAP_QUIET_PART) at src/ekho_impl.h:228
#3  0x000055f1b2a529f9 in ekho::EkhoImpl::synth2 (this=0x7ff25f4a2010, text="实心圆形", 
    callback=0x55f1b2a4d405 <ekho::EkhoImpl::speakPcm(short*, int, void*, ekho::OverlapType)>, userdata=0x7ff25f4a2010)
    at src/libekho_impl.cpp:1962
#4  0x000055f1b2a4f3d3 in ekho::EkhoImpl::speechDaemon (args=0x7ff25f4a2010) at src/libekho_impl.cpp:841
#5  0x00007ff260400609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ff260146103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by hgneng** [comment]
崩溃的问题很可能已经解决了。和多线程处理音频流的逻辑有关。
